import gochujangBowls from "@/assets/gochujang-bowls.jpg";
import salmonTacos from "@/assets/salmon-tacos.jpg";
import tomatoEggRice from "@/assets/tomato-egg-rice.jpg";

import { predictExpiry } from "./shelf-life";
import type { InventoryItem, Meal } from "./types";

const now = new Date();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const inDays = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const SEED_INVENTORY: InventoryItem[] = [
  {
    id: "i1",
    name: "Baby spinach",
    qty: 1,
    unit: "bag",
    category: "produce",
    location: "fridge",
    expiresOn: inDays(2),
    lastConfirmedAt: daysAgo(5),
    captureConfidence: 0.85,
    tags: ["spinach"],
  },
  {
    id: "i2",
    name: "Chicken thighs",
    qty: 1.2,
    unit: "lb",
    category: "meat",
    location: "fridge",
    expiresOn: inDays(1),
    lastConfirmedAt: daysAgo(2),
    captureConfidence: 0.92,
    tags: ["chicken"],
  },
  {
    id: "i3",
    name: "Greek yogurt",
    qty: 2,
    unit: "cup",
    category: "dairy",
    location: "fridge",
    expiresOn: inDays(8),
    lastConfirmedAt: daysAgo(1),
    captureConfidence: 0.9,
    tags: ["greek yogurt", "yogurt"],
  },
  {
    id: "i4",
    name: "Eggs",
    qty: 6,
    unit: "ea",
    category: "dairy",
    location: "fridge",
    expiresOn: inDays(14),
    lastConfirmedAt: daysAgo(3),
    captureConfidence: 0.95,
    tags: ["eggs"],
  },
  {
    id: "i5",
    name: "Brown rice",
    qty: 1,
    unit: "bag",
    category: "grain",
    location: "pantry",
    expiresOn: inDays(300),
    lastConfirmedAt: daysAgo(20),
    captureConfidence: 0.8,
    tags: ["rice"],
  },
  {
    id: "i6",
    name: "Tortillas",
    qty: 1,
    unit: "pack",
    category: "grain",
    location: "fridge",
    expiresOn: inDays(10),
    lastConfirmedAt: daysAgo(4),
    captureConfidence: 0.86,
    tags: ["tortilla"],
  },
  {
    id: "i7",
    name: "Cherry tomatoes",
    qty: 1,
    unit: "pint",
    category: "produce",
    location: "fridge",
    expiresOn: inDays(3),
    lastConfirmedAt: daysAgo(3),
    captureConfidence: 0.84,
    tags: ["tomato"],
  },
  {
    id: "i8",
    name: "Lime",
    qty: 2,
    unit: "ea",
    category: "produce",
    location: "fridge",
    expiresOn: inDays(9),
    lastConfirmedAt: daysAgo(2),
    captureConfidence: 0.9,
    tags: ["lime"],
  },
  {
    id: "i9",
    name: "Gochujang",
    qty: 1,
    unit: "jar",
    category: "condiment",
    location: "fridge",
    expiresOn: inDays(180),
    lastConfirmedAt: daysAgo(30),
    captureConfidence: 0.88,
    tags: ["gochujang"],
  },
  {
    id: "i10",
    name: "Frozen broccoli",
    qty: 1,
    unit: "bag",
    category: "frozen",
    location: "freezer",
    expiresOn: inDays(120),
    lastConfirmedAt: daysAgo(40),
    captureConfidence: 0.78,
    tags: ["broccoli", "frozen vegetables"],
  },
  {
    id: "i11",
    name: "Milk",
    qty: 0.5,
    unit: "gal",
    category: "dairy",
    location: "fridge",
    expiresOn: inDays(4),
    lastConfirmedAt: daysAgo(1),
    captureConfidence: 0.92,
    tags: ["milk"],
  },
  {
    id: "i12",
    name: "Lemon",
    qty: 1,
    unit: "ea",
    category: "produce",
    location: "fridge",
    expiresOn: inDays(7),
    lastConfirmedAt: daysAgo(2),
    captureConfidence: 0.86,
    tags: ["lemon"],
  },
  // Predict-expiry helper to silence the lint if predictExpiry isn't otherwise used elsewhere:
  ...[] as InventoryItem[],
];
void predictExpiry;

export const SEED_MEALS: Meal[] = [
  {
    id: "m-gochu",
    title: "Gochujang Chicken Rice Bowls",
    blurb: "Sticky-spicy chicken over rice, fresh greens on top.",
    image: gochujangBowls,
    minutes: 25,
    effort: "easy",
    method: "stovetop",
    vibe: ["cozy", "indulgent"],
    servings: 2,
    tags: ["chicken", "rice", "spicy", "korean"],
    ingredients: [
      { name: "Chicken thighs", qty: 1, unit: "lb", tags: ["chicken"] },
      { name: "Gochujang", qty: 2, unit: "tbsp", tags: ["gochujang"] },
      { name: "Brown rice", qty: 1, unit: "cup", tags: ["rice"] },
      { name: "Baby spinach", qty: 2, unit: "cup", tags: ["spinach"] },
      { name: "Scallion", qty: 2, unit: "ea", tags: ["scallion"], optional: true },
    ],
    steps: [
      "Cook rice.",
      "Sear chicken in a hot pan, 4 min per side.",
      "Glaze with gochujang + a splash of water.",
      "Wilt spinach in the same pan.",
      "Pile over rice, top with scallion.",
    ],
  },
  {
    id: "m-tacos",
    title: "Quick Salmon Tacos",
    blurb: "Flaky salmon, charred tortillas, bright lime crema.",
    image: salmonTacos,
    minutes: 20,
    effort: "easy",
    method: "stovetop",
    vibe: ["light", "quick"],
    servings: 2,
    tags: ["salmon", "tacos", "fish", "fresh"],
    diet: ["pescatarian"],
    ingredients: [
      { name: "Salmon fillet", qty: 0.8, unit: "lb", tags: ["salmon"] },
      { name: "Tortillas", qty: 6, unit: "ea", tags: ["tortilla"] },
      { name: "Lime", qty: 2, unit: "ea", tags: ["lime"] },
      { name: "Sour cream", qty: 0.5, unit: "cup", tags: ["sour cream"] },
      { name: "Cilantro", qty: 1, unit: "bunch", tags: ["cilantro"], optional: true },
    ],
    steps: [
      "Season salmon, sear skin-side down 4 min.",
      "Flip 2 min, flake into chunks.",
      "Char tortillas over open flame.",
      "Whisk sour cream with lime juice.",
      "Build tacos, finish with cilantro.",
    ],
  },
  {
    id: "m-tomato-egg",
    title: "Tomato Egg Rice",
    blurb: "Silky scrambled eggs over saucy tomatoes, all on rice.",
    image: tomatoEggRice,
    minutes: 15,
    effort: "easy",
    method: "stovetop",
    vibe: ["cozy", "quick"],
    servings: 2,
    tags: ["eggs", "rice", "vegetarian", "tomato"],
    diet: ["vegetarian"],
    ingredients: [
      { name: "Eggs", qty: 4, unit: "ea", tags: ["eggs"] },
      { name: "Cherry tomatoes", qty: 1, unit: "pint", tags: ["tomato"] },
      { name: "Brown rice", qty: 1, unit: "cup", tags: ["rice"] },
      { name: "Scallion", qty: 1, unit: "ea", tags: ["scallion"], optional: true },
    ],
    steps: [
      "Cook rice.",
      "Soft scramble eggs, set aside.",
      "Blister tomatoes in the same pan, splash of water.",
      "Fold eggs back in.",
      "Spoon over rice.",
    ],
  },
  {
    id: "m-sheet-broc",
    title: "Sheet Pan Lemon Chicken & Broccoli",
    blurb: "One pan, 30 minutes, dinner solved.",
    minutes: 30,
    effort: "easy",
    method: "sheet-pan",
    vibe: ["healthy"],
    servings: 3,
    tags: ["chicken", "broccoli", "sheet-pan", "lemon"],
    ingredients: [
      { name: "Chicken thighs", qty: 1.2, unit: "lb", tags: ["chicken"] },
      { name: "Frozen broccoli", qty: 1, unit: "bag", tags: ["broccoli", "frozen vegetables"] },
      { name: "Lemon", qty: 1, unit: "ea", tags: ["lemon"] },
      { name: "Olive oil", qty: 2, unit: "tbsp", tags: ["olive oil"], optional: true },
    ],
    steps: [
      "425°F oven.",
      "Toss everything with oil, salt, pepper, lemon zest.",
      "Roast 25 min until chicken hits 165°F.",
      "Finish with lemon juice.",
    ],
  },
  {
    id: "m-yogurt-bowl",
    title: "Spiced Yogurt Grain Bowl",
    blurb: "No-cook, creamy, crunchy, 10 minutes flat.",
    minutes: 10,
    effort: "easy",
    method: "no-cook",
    vibe: ["light", "healthy", "quick"],
    servings: 1,
    tags: ["yogurt", "vegetarian", "bowl"],
    diet: ["vegetarian"],
    ingredients: [
      { name: "Greek yogurt", qty: 1, unit: "cup", tags: ["greek yogurt", "yogurt"] },
      { name: "Brown rice", qty: 0.5, unit: "cup", tags: ["rice"] },
      { name: "Cherry tomatoes", qty: 0.5, unit: "pint", tags: ["tomato"] },
      { name: "Lemon", qty: 0.5, unit: "ea", tags: ["lemon"] },
    ],
    steps: [
      "Spoon yogurt into a bowl.",
      "Top with rice and tomatoes.",
      "Squeeze lemon, season, eat.",
    ],
  },
  {
    id: "m-pasta-pomodoro",
    title: "Weeknight Pomodoro",
    blurb: "Pantry pasta with a fresh tomato sauce.",
    minutes: 25,
    effort: "easy",
    method: "stovetop",
    vibe: ["cozy"],
    servings: 2,
    tags: ["pasta", "tomato", "italian", "vegetarian"],
    diet: ["vegetarian"],
    ingredients: [
      { name: "Pasta", qty: 0.5, unit: "lb", tags: ["pasta"] },
      { name: "Cherry tomatoes", qty: 1, unit: "pint", tags: ["tomato"] },
      { name: "Garlic", qty: 3, unit: "cloves", tags: ["garlic"] },
      { name: "Parmesan", qty: 0.5, unit: "cup", tags: ["parmesan"], optional: true },
    ],
    steps: [
      "Boil pasta.",
      "Sizzle garlic in oil, add tomatoes, smash.",
      "Toss pasta with sauce + a splash of pasta water.",
      "Shower with parm.",
    ],
  },
  {
    id: "m-air-tofu",
    title: "Air Fryer Crispy Tofu Bowls",
    blurb: "Golden tofu, quick rice, anything-green crunch.",
    minutes: 25,
    effort: "easy",
    method: "air-fryer",
    vibe: ["light", "healthy"],
    servings: 2,
    tags: ["tofu", "vegan", "bowl", "air-fryer"],
    diet: ["vegetarian", "vegan", "dairy-free"],
    ingredients: [
      { name: "Tofu", qty: 1, unit: "block", tags: ["tofu"] },
      { name: "Brown rice", qty: 1, unit: "cup", tags: ["rice"] },
      { name: "Frozen broccoli", qty: 1, unit: "bag", tags: ["broccoli", "frozen vegetables"] },
      { name: "Soy sauce", qty: 2, unit: "tbsp", tags: ["soy"] },
    ],
    steps: [
      "Cube tofu, toss with oil + cornstarch.",
      "Air fry 400°F 15 min, shake halfway.",
      "Cook rice, steam broccoli.",
      "Toss everything in soy.",
    ],
  },
];
